name: Greetings

on: [pull_request_target, issues]

jobs: ORDEN Y DESPACHO
  greeting: BIENVENIDOS A TACOS MISSION 9
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "ELIGE TU MEJOR OPCIÓN' first issue"
        pr-message: "ENVIA TU CONFIRMACIÓN DE PEDIDO Y ESPERA' first pull request"
